# ========================= Project_01 Analysis of Ecommerce store Data ====================== #
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('ecommerce_sales.csv')

print('The first 10 rows of the dataset is given as below.')
print(df.head(10))

print('The last 5 rows of the dataset is given as below.')
print(df.tail(5))

print(f'The numbr of rows in the dataset is {df.shape[0]}')
print(f'The numbr of columns in the dataset is {df.shape[1]}')

print('The column names are as below')
print(df.columns)

print('The data types of each column is:')
print(df.dtypes)

# How many transactions are there?
# As each transaction is represented by a single row and there are 5000 rows so the number of transactions are also 500.

# How many features?
# there are 9 columns so the numer of features are also 9.

# What is the data type of each column?
# The data type of most of the columns are object, two columns are integer, and two columns are float.

print('Missing Values:')
print(df.isnull().sum())

print('Duplicated rows:')
duplicate_rows = df[df.duplicated()]

if not duplicate_rows.empty:
    print("Duplicates found! Processing duplicate rows...")
else:
    print("No duplicates found. The dataset is clean.")

print('Unique products: ')
unique_products = df['product'].unique()
print(unique_products)

print('Unique categories: ')
unique_categories = df['category'].unique()
print(unique_categories)

print('Unique regions: ')
unique_regions = df['region'].unique()
print(unique_regions)

print(f'The number of unique customers are: {df['customer'].nunique()}')


print(f'Total revenue: {df['revenue'].sum()}')
print(f'Average order revenue: {df['revenue'].mean()}')
print(f'Total quantity sold: {df['quantity'].sum()}')
print(f'Average quantity per transaction : {df['quantity'].mean()}')
print(f'Maximum transaction revenue {df['revenue'].max()}')
print(f'Minimum transaction revenue {df['revenue'].min()}')
print(f'Standard deviation of revenue {df['revenue'].std()}')

print(f'The product with most generated revenue is: {df.groupby('product')['revenue'].max().idxmax()}')
print(f'The product with the most sold units is: {df.groupby('product')['quantity'].sum().idxmax()}')
print(f'The average unit price for each product is:\n {df.groupby('product')['unit_price'].mean()}')
print(f'The average discount for each product is:\n {df.groupby('product')['discount'].mean()}')

print(f'Revenue generated by each region is: \n {df.groupby('region')['revenue'].sum()}')
print(f'Region with the most generated revenue: {df.groupby('region')['revenue'].sum().idxmax()}')
print(f'Region with the least generated revenue: {df.groupby('region')['revenue'].sum().idxmin()}')

print(f'Quantity sold by each region is: \n {df.groupby('region')['quantity'].sum()}')
print(f'Region with the most sold quantity: {df.groupby('region')['quantity'].sum().idxmax()}')
print(f'Region with the least sold quantity: {df.groupby('region')['quantity'].sum().idxmin()}')

print(f'Average order value by each region:\n {df.groupby('region')['revenue'].mean()}')

df['order_date'] = pd.to_datetime(df['order_date'])
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month

print('Total revenue for each month')
print(df.groupby('month')['revenue'].sum())
print(f'Highest revenue month: {df.groupby('month')['revenue'].sum().idxmax()}')
print(f'Lowest revenue month: {df.groupby('month')['revenue'].sum().idxmin()}')
print(f'Average revenue per month: {df.groupby('month')['revenue'].sum().mean()}')

print(f'Revenue generated by each category is: \n {df.groupby('category')['revenue'].sum()}')
print(f'Revenue percentage of accessories: {(((df.groupby('category')['revenue'].sum().iloc[0]) / (df['revenue'].sum())) *100).round(2)}%')
print(f'Revenue percentage of electronics: {(((df.groupby('category')['revenue'].sum().iloc[1]) / (df['revenue'].sum())) *100).round(2)}%')
print(f'Revenue percentage of clothing: {(((df.groupby('category')['revenue'].sum().iloc[2]) / (df['revenue'].sum())) *100).round(2)}%')


top_10_customers = df.groupby('customer')['revenue'].sum().sort_values(ascending=False).head(10)
print(top_10_customers)

print(f'Average revenue per customer: {df.groupby('customer')['revenue'].sum().mean().round(2)}')
print(f'Median revenue per customer: {df.groupby('customer')['revenue'].sum().median()}')
print(f'Minimum revenue per customer: {df.groupby('customer')['revenue'].sum().min()}')

p25 = df['revenue'].quantile(0.25)
p50 = df['revenue'].quantile(0.50)  
p75 = df['revenue'].quantile(0.75)

print(f"25th Percentile (Q1): {p25}")
print(f"50th Percentile (Median): {p50}")
print(f"75th Percentile (Q3): {p75}")

iqr = p75 - p25
lower_bound = p25 - 1.5 * iqr
upper_bound = p75 + 1.5 * iqr

number_of_outliers = df[(df['revenue'] < lower_bound) | (df['revenue'] > upper_bound)].shape[0]
print(f"Number of outliers in revenue: {number_of_outliers}")

percentage_of_outliers = (number_of_outliers / df.shape[0]) * 100
print(f"Percentage of outliers in revenue: {percentage_of_outliers:.2f}%")

# visualization 01

plt.figure(figsize=(10, 7), dpi=120)
product = df['product'].unique()
revenue = df.groupby('product')['revenue'].sum()
plt.bar(
    product,
    revenue,
    color='green',
    width=0.6
)
plt.title('Revenue by product')
plt.xlabel('Products')
plt.ylabel('Revenue')
plt.grid(axis='y')
# plt.show()

# visualization 02

plt.figure(figsize=(10, 7), dpi=120)
region = df['region'].unique()
revenue = df.groupby('region')['revenue'].sum()
plt.bar(
    region,
    revenue,
    color='teal',
    width=0.5
)
plt.title('Revenue by region')
plt.xlabel('Regions')
plt.ylabel('Revenue')
plt.grid(axis='y')
# plt.show()

# visualization 03
plt.figure(figsize=(10, 7), dpi=120)
months = df['month'].unique()
revenue = df.groupby('month')['revenue'].sum()
plt.plot(
    months,
    revenue,
    marker='o',
    lw=2,
    color='skyblue',
    label='Monthly Revenue'
)
plt.title('Monthly Revenue Graph')
plt.xlabel('Months')
plt.ylabel('Revenue')
plt.grid()
plt.legend()
# plt.show()

# visualization 04
plt.figure(figsize=(10, 7), dpi=120)
revenue = df['revenue']
plt.hist(
    revenue,
    bins=10,
    color='lightgreen',
    edgecolor='black'
)
plt.title('Revenue Distribution')
plt.xlabel('Revenue')
plt.ylabel('Frequency')
plt.grid()
# plt.show()

# visualization 05
plt.figure(figsize=(10, 7), dpi=120)
quantity = df['quantity']
revenue = df['revenue']
plt.scatter(
    quantity,
    revenue,
    color="purple",
    s=120,
    marker="D",
)
plt.title("Quantity vs Revenue")
plt.xlabel("Quantity")
plt.ylabel("Revenue")
plt.grid()

# plt.show()

# visualization 06
plt.figure(figsize=(10, 7), dpi=120)
category = df['category'].unique()
revenue = df.groupby('category')['revenue'].sum()
plt.bar(
    category,
    revenue,
    color='brown',
    width=0.7
)
plt.title('Revenue by Category')
plt.xlabel('Category')
plt.ylabel('Revenue')
plt.grid(axis='y')
# plt.show()

# Final Dashboard
fig, ax = plt.subplots(3, 2, figsize=(12, 9), dpi=120)

product = df['product'].unique()
revenue = df.groupby('product')['revenue'].sum()
ax[0, 0].bar(
    product,
    revenue,
    color='green',
    width=0.6
)
ax[0,0].set_title('Revenue by product')
ax[0,0].set_xlabel('Products')
ax[0,0].set_ylabel('Revenue')
ax[0,0].grid(axis='y')

region = df['region'].unique()
revenue = df.groupby('region')['revenue'].sum()
ax[0, 1].bar(
    region,
    revenue,
    color='teal',
    width=0.5
)
ax[0, 1].set_title('Revenue by region')
ax[0, 1].set_xlabel('Regions')
ax[0, 1].set_ylabel('Revenue')
ax[0, 1].grid(axis='y')

months = df['month'].unique()
revenue = df.groupby('month')['revenue'].sum()
ax[1, 0].plot(
    months,
    revenue,
    marker='o',
    lw=2,
    color='skyblue',
    label='Monthly Revenue'
)
ax[1, 0].set_title('Monthly Revenue Graph')
ax[1, 0].set_xlabel('Months')
ax[1, 0].set_ylabel('Revenue')
ax[1, 0].grid()
ax[1, 0].get_legend()

revenue = df['revenue']
ax[1, 1].hist(
    revenue,
    bins=10,
    color='lightgreen',
    edgecolor='black'
)
ax[1, 1].set_title('Revenue Distribution')
ax[1, 1].set_xlabel('Revenue')
ax[1, 1].set_ylabel('Frequency')
ax[1, 1].grid()

quantity = df['quantity']
revenue = df['revenue']
ax[2, 0].scatter(
    quantity,
    revenue,
    color="purple",
    s=120,
    marker="D",
)
ax[2, 0].set_title("Quantity vs Revenue")
ax[2, 0].set_xlabel("Quantity")
ax[2, 0].set_ylabel("Revenue")
ax[2, 0].grid()

category = df['category'].unique()
revenue = df.groupby('category')['revenue'].sum()
ax[2, 1].bar(
    category,
    revenue,
    color='brown',
    width=0.7
)
ax[2, 1].set_title('Revenue by Category')
ax[2, 1].set_xlabel('Category')
ax[2, 1].set_ylabel('Revenue')
ax[2, 1].grid(axis='y')

plt.tight_layout()
plt.savefig('revenue_analysis_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()