#==================================== Rounding Universal Functions ===================================#
import numpy as np

arr_01 = np.random.uniform(2500, 12000, 500)
arr_01 = np.round(arr_01, 2)
avg_bonus = np.average(arr_01)
high_bonuses = np.sum(arr_01 > 900)
max_bonus = np.max(arr_01)
min_bonus = np.min(arr_01)
print(f'Average Bonus : {avg_bonus}')
print(f'Number of Bonuses > 9000 : {high_bonuses}')
print(f'Maximum Bonus : {max_bonus}')
print(f'Minimum Bonus : {min_bonus}')

arr_02 = np.random.normal(loc=35.5, scale=1.8, size=(10,6))
arr_02a = np.floor(arr_02)
arr_02b = np.ceil(arr_02)
print(f'Array A : {arr_02a}')
print(f'Array B : {arr_02b}')
print(f'Difference Betwee Overall Mean : {np.subtract(np.mean(arr_02a), np.mean(arr_02b))}')
print(f'Number of Elements Changed : {np.sum(arr_02 != arr_02a)}')

arr_03 = np.random.normal(loc=15, scale=2.5, size=1000)
arr_03a = np.trunc(arr_03)
arr_03b = np.round(arr_03)
diff_count = np.sum(arr_03 != arr_03a & arr_03b)
avg = np.mean(np.mean(arr_03a), np.mean(arr_03b))
if np.mean(arr_03a) > np.mean(arr_03b):
    print(f'Truncate Method Gives Larger Average')
else:
    print(f'Round Method Gives Larger Average.')

arr_04 = np.random.uniform(18.5, 43.7, (24,60))
arr_04a = np.round(arr_04, 1)
avg_temp = np.mean(arr_04a, axis=1)
max_avg = np.argmax(arr_04a, axis=1)
min_avg = np.argmin(arr_04a, axis=1)
high_count = np.sum(arr_04a > 40)

arr_05 = np.random.normal(loc=120, scale=18, size=750)
floor_array = np.floor(arr_05)
ceil_array = np.ceil(arr_05)
round_array = np.round(arr_05)
trunc_array = np.trunc(arr_05)
print(f'Mean of Floor Array : {np.mean(floor_array)}')
print(f'Mean of Ceil Array : {np.mean(ceil_array)}')
print(f'Mean of Round Array : {np.mean(round_array)}')
print(f'Mean of Trunc Array : {np.mean(trunc_array)}')
print(f'Maximum Value of Floor Array : {np.mean(floor_array)}')
print(f'Maximum Value of Ceil Array : {np.mean(ceil_array)}')
print(f'Maximum Value of Round Array : {np.mean(round_array)}')
print(f'Maximum Value of Trunc Array : {np.mean(trunc_array)}')
print(f'Values Greater Than 140 in Floor : {np.sum(floor_array > 140)}')
print(f'Values Greater Than 140 in Ceil : {np.sum(ceil_array > 140)}')
print(f'Values Greater Than 140 in Round : {np.sum(round_array > 140)}')
print(f'Values Greater Than 140 in Trunc : {np.sum(trunc_array > 140)}')