#=============================== Trignometric Universal Functions ================================#
import numpy as np

angles = np.random.randint(0, 361, 200)
rad = np.deg2rad(angles)
sin_val = np.sin(rad)
avg_sin = np.mean(sin_val)
high_vals = np.sum(sin_val > 0.8)
max_angle = np.argmax(np.sin(rad))

angles = np.random.randint(-180,181,(8,6))
rad = np.deg2rad(angles)
cos_val = np.cos(rad)
avg_cos = np.mean(cos_val, axis=1)
high_val = np.argmax(np.mean(cos_val, axis=1))
neg_val = np.sum(cos_val < 0)

angles = np.random.randint(1,89,300)
rad = np.deg2rad(angles)
tan_val = np.tan(rad)
max_tan = np.max(tan_val)
min_tan = np.min(tan_val)
high_val = np.sum(tan_val > 2)
avg_tan = np.mean(tan_val)

values = np.random.uniform(-1,1,500)
sin_val = np.arcsin(values)
deg_val = np.rad2deg(sin_val)
max_angle = np.max(deg_val)
min_angle = np.min(deg_val)
high_angles = np.sum(deg_val > 45)

angles = np.random.randint(0,91,1000)
rad = np.deg2rad(angles)
sin_values = np.sin(rad)
cos_values = np.cos(rad)
tan_values = np.tan(rad)
mean_sin = np.mean(sin_values)
mean_cos = np.mean(cos_values)
mean_tan = np.mean(tan_values)
max_avg = np.argmax([mean_sin, mean_cos, mean_tan])
tan_val5 = np.sum(tan_values > 5)
max_tan = np.max(tan_values)
max_rad = np.argmax(max_tan)
deg_max = np.rad2deg(max_rad)
print(f'The Max Tan {max_tan} has the following angle {deg_max}')