#================================ Statistical Universal Functions ==============================#
import numpy as np

salary = np.random.randint(30000, 150001, 1000)
print(f'Mean : {np.mean(salary)}')
print(f'Median : {np.median(salary)}')
print(f'Variance : {np.var(salary)}')
print(f'Standard Deviation : {np.std(salary)}')
print(f'25th Percentile : {np.percentile(salary, 25)}')
print(f'50th Percentile : {np.percentile(salary, 50)}')
print(f'90th Percentile : {np.percentile(salary, 90)}')
print(f'Index of Highest Salary : {np.argmax(salary)}')
print(f'Salaries Above the Mean : {np.sum(salary > np.mean(salary))}')
print(f'-'*60)

marks = np.random.randint(0, 101, (15, 40))
print(f'Average Marks of Each Class : {np.mean(marks, axis=1)}')
print(f'Class With Highest Average : {np.argmax(marks, axis=1)}')
print(f'Median Marks of Each Class : {np.median(marks, axis=1)}')
print(f'The overall Variance : {np.var(marks)}')
print(f'Number of Students Scoring above median : {np.sum(marks > np.median(marks))}')
print('-'*60)

sensor = np.random.normal(loc=75, scale=8, size=(24, 60))
print(f'Hourly Average : {np.mean(sensor, axis=1)}')
print(f'Hour With Highest Average : {np.argmax(sensor, axis=1)}')
print(f'Overall Median : {np.median(sensor)}')
print(f'95Th Percentile : {np.percentile(sensor, 95)}')
print(f'Number of Readings Above 95Th Percentile : {np.sum(sensor > np.percentile(sensor, 95))}')
print('-'*60)

rain = np.random.uniform(0, 200, 365)
print(f'Yearly Average Rainfall : {np.mean(rain)}')
print(f'Rainiest Day Index : {np.argmax(rain)}')
print(f'Rainiest Day Value : {np.max(rain)}')
print(f'Median Rainfall : {np.median(rain)}')
print(f'Variance Rainfall : {np.var(rain)}')
print(f'Number of Days greater than 75th Percentile : {np.sum(rain > np.percentile(rain, 75))}')
print('-'*60)

confidence = np.random.uniform(0, 1, (20, 50))
print(f'The Average Confidence of Each Model : {np.mean(confidence, axis=1)}')
print(f'The Best performing Model is : {np.argmax(confidence)}')
print(f'The overall median confidence : {np.median(confidence)}')
print(f'The 90Th Percentile : {np.percentile(confidence, 90)}')
print(f'Percentage of above overall mean : ')
print('-'*60)