#========================================= Uniform Distribution in NumPy ============================================== #
import numpy as np

arr_01 = np.random.uniform(10, 40, 10)
print(f'Array : {arr_01}')
print(f'Mean  : {np.mean(arr_01)}')
print(f'Max  : {np.max(arr_01)}')
print(f'Min  : {np.min(arr_01)}')
print('-'*50)

arr_02 = np.random.uniform(30000, 80000, 15)
print(f'Array : {arr_02}')
print(f'Mean  : {np.mean(arr_02)}')
print(f'Max  : {np.max(arr_02)}')
print(f'Min  : {np.min(arr_02)}')
print(f'Std  : {np.std(arr_02)}')
print('-'*50)

arr_03 = np.random.uniform(150, 190, 25)
print(f'Array : {arr_03}')
print(f'Avg  : {np.average(arr_03)}')
print(f'Max  : {np.max(arr_03)}')
print(f'Min  : {np.min(arr_03)}')
print('-'*50)

arr_04 = np.random.uniform(1, 5, 20)
print(f'Array : {arr_04}')
print(f'Mean  : {np.mean(arr_04)}')
print(f'Std  : {np.std(arr_04)}')
print('-'*50)

arr_05 = np.random.uniform(500, 5000, 30)
print(f'Array : {arr_05}')
print(f'Mean  : {np.mean(arr_05)}')
print(f'Max  : {np.max(arr_05)}')
print(f'Min  : {np.min(arr_05)}')
print('-'*50)

arr_06 = np.random.uniform(0, 100, 50) 
print(f'Mean  : {np.mean(arr_06)}')
print(f'Std  : {np.std(arr_06)}')
print(f'Max  : {np.max(arr_06)}')
print(f'Min  : {np.min(arr_06)}')
print('-'*50)

arr_07 = np.random.uniform(-100, 100, 40)
print(f'Array : {arr_07}')
print(f'Mean  : {np.mean(arr_07)}')
print(f'Max  : {np.max(arr_07)}')
print(f'Min  : {np.min(arr_07)}')
print('-'*50)

arr_08 = np.random.uniform(10, 50, (4,5))
print(f'Array : {arr_08}')
print(f'Shape : {np.shape(arr_08)}')
print(f'Mean : {np.mean(arr_08)}')
print(f'Std : {np.std(arr_08)}')
print(f'Max : {np.max(arr_08)}')
print(f'Min : {np.min(arr_08)}')
print('-'*50)